version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: social-recipes-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning

  bull-monitor:
    image: ejhayes/nodejs-bull-monitor:latest
    ports:
      - 8675:8675
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 8675
    depends_on:
      redis:
        condition: service_started

volumes:
  redis-data:
    driver: local
